server:
  port: 8202
spring:
  application:
    name: service-cmn
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/yygh_cmn?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: root
    password: hjb210907
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 192.168.200.130
    port: 6379
    lettuce:
      pool:
        max-active: 20
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

