server:
  port: 8160
spring:
  application:
    name: service-user
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/yygh_user?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: hjb210907
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    database: 0
    host: 192.168.200.130
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 1800000

mybatis-plus:
  mapper-locations: classpath:com/donn/yygh/user/mapper/xml/*.xml

weixin:
  appid: wxed9954c01bb89b47
  appsecret: a7482517235173ddb4083788de60b90e
  redirecturl: http://localhost:8160/user/userInfo/wx/callback

